development:
      host: 127.0.0.1
      adapter: mysql2
      database: cms
      port: 3306
      username: root
      password: vinner

test: &test
      host: 127.0.0.1
      adapter: mysql2
      database: cms
      port: 3306
      username: root
      password: vinner

production:
      host: 127.0.0.1
      adapter: mysql2
      database: cms
      port: 3306
      username: root
      password: vinner
cucumber:
  <<: *test
