development:
  adapter: postgresql
  host:	ec2-54-197-241-91.compute-1.amazonaws.com
  database:	d8h40f8ekc8936
  user:	bpovpbioixdkmc
  port:	5432
  password:	i-Meh0UmasLTPEab6hxyDCjsnf
  psql:	heroku pg:psql --app tamilnaduliveonline mauve
  URL:	postgres://bpovpbioixdkmc:i-Meh0UmasLTPEab6hxyDCjsnf@ec2-54-197-241-91.compute-1.amazonaws.com:5432/d8h40f8ekc8936
test:
  adapter: postgresql
  host:	ec2-54-197-241-91.compute-1.amazonaws.com
  database:	d8h40f8ekc8936
  user:	bpovpbioixdkmc
  port:	5432
  password:	i-Meh0UmasLTPEab6hxyDCjsnf
  psql:	heroku pg:psql --app tamilnaduliveonline mauve
  URL:	postgres://bpovpbioixdkmc:i-Meh0UmasLTPEab6hxyDCjsnf@ec2-54-197-241-91.compute-1.amazonaws.com:5432/d8h40f8ekc8936
production:
adapter: postgresql
  host:	ec2-54-225-103-9.compute-1.amazonaws.com
  database:	dbt29f7h55lo9
  user:	wekaeygcqruqzk
  port:	5432
  password:	N9B5k6pOKr57BSLkrICsBhmYjm
  psql:	heroku pg:psql --app tamilnaduliveonline gold
  URL:	Hide postgres://wekaeygcqruqzk:N9B5k6pOKr57BSLkrICsBhmYjm@ec2-54-225-103-9.compute-1.amazonaws.com:5432/dbt29f7h55lo9